### ISSUE TITLE
A private Gist

### ISSUE THREAD

**Issue by miki-tebe** [piedcipher/dotslash3.0#4]
The current code makes all gist public but you can change the code in the Axios request into 'public': false to make your gist private. It is also cool if we have an option to make it either public or private.

**Comment by piedcipher** [comment]
Thanks for the feature request. I'll add an option to choose gist privacy.

**Comment by piedcipher** [comment]
I've just added this feature in VSCode Extension :tada:

![](https://imgur.com/oAUV5rY.png)

**Comment by miki-tebe** [comment]
Thank you.

**Comment by piedcipher** [comment]
You're welcome. I'll soon publish this to VSCode marketplace.

**Comment by miki-tebe** [comment]
Yaa that too will be very helpful

**Comment by piedcipher** [comment]
Hi @miki-tebe, it is now available as VSCode Extension.

https://marketplace.visualstudio.com/items?itemName=piedcipher.dartpad-generator
