### ISSUE TITLE
Not working in vscode

### ISSUE THREAD

**Issue by bsutton** [piedcipher/dotslash3.0#6]
I'm using dart-code 3.17.0.

I've installed dartpad generator 0.0.1.

When I run dart pad generated for my example.dart it does literally nothing.

In you little example gif it appears to actually start a debug session?

It would be helpful to have some text describing the process as I've had to watch the gif multiple times to try and work out how to use the tool.

**Comment by piedcipher** [comment]
Thank you for opening this issue. 

Have you added the personal access token in plugin (dartpad generator) settings?

Here's a guide for that: https://github.com/piedcipher/dotslash3.0/tree/master/dartpad_gen_vscode/dartpad-generator#extension-settings
